# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/envs.conf

# add tags for games
windowrule {
  name = tag-games
  match:class = (Is This Seat Taken.x86_64|factorio|Goodbye Eternity|StardewModdingAP|Megabonk.x86_64|Terraria.bin.x86_64)
  tag = +game
}
windowrule {
  name = games
  match:tag = game
  workspace = 5
  fullscreen = on
}
# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu
windowrule {
  name = youtube
  match:class = chrome-youtube.com__-Default
  workspace = 10 silent
}
windowrule {
  name = ytmusic
  match:class = chrome-music.youtube.com__-Default
  workspace = 10 silent
  opacity = 0.85
}
windowrule {
  name = leetcode
  match:class = chrome-leetcode.com__problemset_-Default
  workspace = 1
  opacity = 0.9
}
windowrule {
  name = obsidian
  match:class = obsidian
  workspace = special:scratchpad
  opacity = 0.9
}
windowrule {
  name = scratchpad
  match:workspace = special:scratchpad
  opacity = 0.8
}
windowrule {
  name = steam
  match:class = (steam|net.lutris.Lutris)
  workspace = 6 silent
}
windowrule {
  name = steam-bpm
  match:title = Steam Big Picture Mode
  workspace = 6 silent
  fullscreen = on
  opacity = 0.85
}
windowrule {
  name = ghostty
  match:class = com.mitchellh.ghostty
  opacity = 0.9
}
windowrule {
  name = boot.dev
  match:title = .*Boot.dev - Chromium.*
  workspace = 2
  opacity = 0.9
}
windowrule {
  name = librewolf
  match:class = librewolf
  workspace = 2
}

